name: Writing Style Review

on:
  pull_request:
    paths:
      - '_notes/**/*.md'
      - '_essays/**/*.md'
      - '_posts/**/*.md'
    types: [ready_for_review, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history to compare with base branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r .github/scripts/requirements.txt

      - name: Review writing style
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_NAME: ${{ github.repository }}
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          python .github/scripts/review-writing.py
